version: "3.7"
services:
    # image project
    app:
        container_name: laravel-app
        build:
          args:
            "user": "awgoncalves"
            "uid": "9999"
          context: .
          dockerfile: ./docker/Dockerfile
        image: laravel-app/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravelApp
    
    # nginx
    nginx:
        container_name: laravel-app-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravelApp

    # db mysql
    mysql:
        container_name: laravel-app-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3308:3306"
        networks: 
            - laravelApp

    # queue
    queue:
        container_name: especializati-queue
        image: laravel-app/laravel-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - laravelApp

    # redis
    redis:
        container_name: laravel-app-redis
        image: redis:latest
        networks: 
            - laravelApp

networks: 
    laravelApp:
        driver: bridge